### ISSUE TITLE
Amusewiki is not running after update amusewiki packages (Ubuntu 18.04.6 LTS)

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/amusewiki#389]
For long time my testing amusewiki interface is was working around but after update not working anymore.

```
Mar 26 00:01:24 testing plackup[2882]: Error while loading /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi: Can't locate object method "locale_data" via package "DateTime::Locale::FromData" at /usr/share/perl5/AmuseWikiFarm/Utils/Amuse.pm line 1054.
Mar 26 00:01:24 testing plackup[2882]: Compilation failed in require at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
Mar 26 00:01:24 testing plackup[2882]: BEGIN failed--compilation aborted at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
```

I also tried on clean installation but still getting this error:

#### journalctl -u amusewiki-jobber.service

```
Mar 25 20:37:16 testing amusewiki-jobber[27236]: Can't locate object method "locale_data" via package "DateTime::Locale::FromData" at /usr/share/perl5/AmuseWikiFarm/Utils/Amuse.pm line 1054.
Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Main process exited, code=exited, status=255/n/a
Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Failed with result 'exit-code'.
Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Service hold-off time over, scheduling restart.
Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Scheduled restart job, restart counter is at 15.
Mar 25 20:37:16 testing systemd[1]: Stopped Amusewiki jobber.
Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Start request repeated too quickly.
Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Failed with result 'exit-code'.
Mar 25 20:37:16 testing systemd[1]: Failed to start Amusewiki jobber.
```

#### journalctl -u amusewiki-web.service
```
Mar 25 20:36:52 testing systemd[1]: Started Amusewiki web server.
Mar 25 20:36:54 testing plackup[27198]: Error while loading /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi: Can't locate object method "locale_data" via package "DateTime::Locale::FromData" at /usr/share/perl5/AmuseWikiFarm/Utils/Amuse.pm line 1054.
Mar 25 20:36:54 testing plackup[27198]: Compilation failed in require at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
Mar 25 20:36:54 testing plackup[27198]: BEGIN failed--compilation aborted at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Main process exited, code=exited, status=255/n/a
Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Failed with result 'exit-code'.
Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Service hold-off time over, scheduling restart.
Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Scheduled restart job, restart counter is at 3.
Mar 25 20:36:54 testing systemd[1]: Stopped Amusewiki web server.
```

#### cat /etc/os-release 
```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

#### cat /etc/debian_version 
```
buster/sid
```
> Note: amusewiki buster source not working on Ubuntu 18.04/ buster, only stretch source is working. 

#### cat /etc/apt/sources.list.d/amusewiki.list 
```
deb http://packages.amusewiki.org/debian stretch main
```

**Comment by melmothx** [comment]
Rojen Zaman ***@***.***> writes:

> For long time my testing amusewiki interface is was working around but
> after update not working anymore.

Ok, I see the problem. The DateTime::Locale module is too old for this.

I'm going to put out a fix over the next days.

Thanks for the report.

> ```
> Mar 26 00:01:24 testing plackup[2882]: Error while loading /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi: Can't locate object method "locale_data" via package "DateTime::Locale::FromData" at /usr/share/perl5/AmuseWikiFarm/Utils/Amuse.pm line 1054.
> Mar 26 00:01:24 testing plackup[2882]: Compilation failed in require at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
> Mar 26 00:01:24 testing plackup[2882]: BEGIN failed--compilation aborted at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
> ```
>
> I also tried on clean installation but still getting this error:
>
>
> #### journalctl -u amusewiki-jobber.service
>
> ```
> Mar 25 20:37:16 testing amusewiki-jobber[27236]: Can't locate object method "locale_data" via package "DateTime::Locale::FromData" at /usr/share/perl5/AmuseWikiFarm/Utils/Amuse.pm line 1054.
> Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Main process exited, code=exited, status=255/n/a
> Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Failed with result 'exit-code'.
> Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Service hold-off time over, scheduling restart.
> Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Scheduled restart job, restart counter is at 15.
> Mar 25 20:37:16 testing systemd[1]: Stopped Amusewiki jobber.
> Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Start request repeated too quickly.
> Mar 25 20:37:16 testing systemd[1]: amusewiki-jobber.service: Failed with result 'exit-code'.
> Mar 25 20:37:16 testing systemd[1]: Failed to start Amusewiki jobber.
> ```
>
> #### journalctl -u amusewiki-web.service
> ```
> Mar 25 20:36:52 testing systemd[1]: Started Amusewiki web server.
> Mar 25 20:36:54 testing plackup[27198]: Error while loading /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi: Can't locate object method "locale_data" via package "DateTime::Locale::FromData" at /usr/share/perl5/AmuseWikiFarm/Utils/Amuse.pm line 1054.
> Mar 25 20:36:54 testing plackup[27198]: Compilation failed in require at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
> Mar 25 20:36:54 testing plackup[27198]: BEGIN failed--compilation aborted at /usr/share/perl5/AmuseWikiFarm/psgi/amusewiki.psgi line 7.
> Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Main process exited, code=exited, status=255/n/a
> Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Failed with result 'exit-code'.
> Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Service hold-off time over, scheduling restart.
> Mar 25 20:36:54 testing systemd[1]: amusewiki-web.service: Scheduled restart job, restart counter is at 3.
> Mar 25 20:36:54 testing systemd[1]: Stopped Amusewiki web server.
> ```
>
> #### cat /etc/os-release 
> ```
> NAME="Ubuntu"
> VERSION="18.04.6 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.6 LTS"
> VERSION_ID="18.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic
> ```
>
> #### cat /etc/debian_version 
> ```
> buster/sid
> ```
>> Note: amusewiki buster source not working on Ubuntu 18.04/ buster, only stretch source is working. 
>
>
> #### cat /etc/apt/sources.list.d/amusewiki.list 
> ```
> deb http://packages.amusewiki.org/debian stretch main
> ```


-- 
Marco

**Comment by melmothx** [comment]
A new package has been published which I believe it should fix the issue.

**Comment by rojenzaman** [comment]
Thanks for update, now it is working!

```
root@testing:~# cat /var/mail/root
2022/03/26 18:35:59 ERROR - AmuseWikiFarm.Utils.Amuse - /usr/share/perl5/AmuseWikiFarm/Utils/Amuse.pm:1073 - Failed to load DateTime::Locale for ceb and cannot create a surrogate. You will not be able to use Cebuano in the interface, unless you upgrade DateTime::Locale

root@testing:~# journalctl -u amusewiki-jobber.service 
-- Logs begin at Fri 2022-03-25 19:02:54 UTC, end at Sat 2022-03-26 18:40:27 UTC. --
Mar 26 18:35:55 testing systemd[1]: Started Amusewiki jobber.
Mar 26 18:36:02 testing amusewiki-jobber[9288]: Starting jobber's loop with polling interval of 5 seconds with pid 9288
Mar 26 18:36:02 testing amusewiki-jobber[9288]: Lockfile is .amusewiki.jobber.lock
Mar 26 18:36:02 testing amusewiki-jobber[9288]: Max parallel jobs: 3

root@testing:~# journalctl -u amusewiki-web.service 
-- Logs begin at Fri 2022-03-25 19:02:54 UTC, end at Sat 2022-03-26 18:40:27 UTC. --
Mar 26 18:35:55 testing systemd[1]: Started Amusewiki web server.
Mar 26 18:36:02 testing plackup[9289]: FastCGI: manager (pid 9289): initialized
Mar 26 18:36:02 testing plackup[9289]: FastCGI: manager (pid 9289): server (pid 10501) started
Mar 26 18:36:02 testing plackup[9289]: FastCGI: manager (pid 9289): server (pid 10502) started
Mar 26 18:36:02 testing plackup[9289]: FastCGI: manager (pid 9289): server (pid 10507) started
Mar 26 18:36:02 testing plackup[9289]: FastCGI: manager (pid 9289): server (pid 10511) started

```
